//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Tests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Tests.TestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID,Student Number,First Name,Last Name,Has Scholarship
        ///1,PT300,Tom,Petty,No
        ///2,JB600,Billy ,Joel,No
        ///3,JM900,Michael,Jorden,Yes
        ///4,FH1200,Harrison,Ford,No
        ///5,DC1500,Celine,Dion,No
        ///6,HT1800,Tom,Hanks,No
        ///7,HH2100,Helen,Hunt,No
        ///8,RJ2400,Julia,Roberts,Yes
        ///9,PK2700,Katy,Perry,No
        ///10,JA3000,Angelina,Jolie,No
        ///11,JL3300,LeBron,James,No.
        /// </summary>
        internal static string Interview_Data_Students {
            get {
                return ResourceManager.GetString("Interview_Data_Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher ID,First Name,Last Name
        ///1,Elliot,Gould
        ///2,Christina,Pickles
        ///3,Larry,Hankin
        ///4,Lisa,Kudrow
        ///.
        /// </summary>
        internal static string Interview_Data_Teachers {
            get {
                return ResourceManager.GetString("Interview_Data_Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a dfsjkl;fsajdfsa jdfads 0j a 0tjtr0j0 tt 4 t4 y5 hh ta jhthtrs  htr h hdsr.
        /// </summary>
        internal static string junkFile {
            get {
                return ResourceManager.GetString("junkFile", resourceCulture);
            }
        }
    }
}
